# Update these values for your GitHub org and SonarQube project.
sonar.projectKey=wallet-transfer-assignment
sonar.projectName=wallet-transfer-assignment
sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.exclusions=**/.git/**,**/.github/**,**/vendor/**,**/node_modules/**,**/coverage/**,**/migrations/**
